//
// DO NOT EDIT
//
// Generated by swift-atproto
//
// swift-format-ignore-file

import SwiftAtproto

public enum UnknownATPValue: UnknownATPValueProtocol {
  case record(any ATProtoRecord)
  case any(any Codable & Hashable & Sendable)

  public static let allTypes: [String: any ATProtoRecord.Type] = [
    "app.bsky.feed.like": App.Bsky.FeedLike.self,
    "app.bsky.feed.post": App.Bsky.FeedPost.self,
    "app.bsky.feed.postgate": App.Bsky.FeedPostgate.self,
    "app.bsky.feed.repost": App.Bsky.FeedRepost.self,
    "app.bsky.feed.threadgate": App.Bsky.FeedThreadgate.self,
    "app.bsky.graph.block": App.Bsky.GraphBlock.self,
    "app.bsky.graph.follow": App.Bsky.GraphFollow.self,
    "app.bsky.notification.declaration": App.Bsky.NotificationDeclaration.self,
    "com.germnetwork.declaration": Com.Germnetwork.Declaration.self,
  ]

  public var type: String? {
    switch self {
    case .record(let record):
      return Swift.type(of: record).nsId
    case .any:
      return nil
    }
  }

  public var val: any Codable & Hashable & Sendable {
    switch self {
    case .record(let record):
      record
    case .any(let object):
      object
    }
  }
}
